package auth

// #141 / #146 (L1c) — reference verifier (oracle), mutants, and the table of conformance checks.
//
// The same table (specLinkCases) is run against:
//   - the ORACLE (a small, correct verifier written here): it must pass every case — this proves the
//     cases themselves are right;
//   - three MUTANTS of the oracle ("aud not verified", "previous kid always accepted", "seq not
//     verified"): each must FAIL at least the cases named for it — this proves the cases bite;
//   - the REAL implementation (linkjwt_spec_test.go), once the dev wires it.

import (
	"crypto/ecdsa"
	"crypto/ed25519"
	"crypto/elliptic"
	"crypto/rand"
	"crypto/rsa"
	"crypto/sha256"
	"crypto/x509"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"strings"
	"sync"
	"testing"
	"time"

	"github.com/golang-jwt/jwt/v5"
)

// ── oracle ───────────────────────────────────────────────────────────────────

type specMutant string

const (
	specNoMutant              specMutant = ""
	specMutAudIgnored         specMutant = "aud-not-verified"
	specMutPrevAlwaysOK       specMutant = "previous-kid-always-accepted"
	specMutSeqIgnored         specMutant = "seq-not-verified"
	specMutIssIgnored         specMutant = "iss-not-verified"
	specKidLen                           = 12
	specLegacyRoleRelay                  = "relay"
	specRoleChild                        = "relay-child"
	specRoleParent                       = "relay-parent"
	specRootID                           = "root"
	specChildID, specParentID            = "relay-x", "relay-p"
)

// every key ever generated by a case, by kid: what the "previous always accepted" mutant remembers
var (
	specAllKeysMu sync.Mutex
	specAllKeys   = map[string]ed25519.PublicKey{}
)

func specRefKid(pub ed25519.PublicKey) string {
	h := sha256.Sum256(pub)
	return base64.RawURLEncoding.EncodeToString(h[:specKidLen])
}

type specRevMsg struct {
	Seq     uint64         `json:"seq"`
	Entries []specRevEntry `json:"entries"`
	Sig     []byte         `json:"sig"`
}

type specKeysMsg struct {
	CurrentPub  []byte `json:"current_pub"`
	PreviousPub []byte `json:"previous_pub"`
	Seq         uint64 `json:"seq"`
	Sig         []byte `json:"sig"`
}

func specRevPayload(seq uint64, e []specRevEntry) []byte {
	b, _ := json.Marshal(struct {
		Seq     uint64         `json:"seq"`
		Entries []specRevEntry `json:"entries"`
	}{seq, e})
	return b
}

func specKeysPayload(newCur, prev ed25519.PublicKey, seq uint64) []byte {
	b, _ := json.Marshal(struct {
		C, P []byte
		S    uint64
	}{newCur, prev, seq})
	return b
}

// specOracle builds the reference implementation, optionally mutated.
func specOracle(m specMutant) *specLinkImpl {
	impl := &specLinkImpl{KidOf: specRefKid, Code: func(err error) string {
		for _, c := range []string{"jwt_missing_kid", "jwt_unknown_kid", "jwt_missing_aud", "jwt_wrong_aud", "jwt_wrong_issuer"} {
			if strings.Contains(err.Error(), c) {
				return c
			}
		}
		return err.Error()
	}}

	impl.VerifyToken = func(trust specLinkTrust, token string, want specLinkWant, now time.Time) (bool, error) {
		p := jwt.NewParser(jwt.WithValidMethods([]string{"EdDSA"}), jwt.WithTimeFunc(func() time.Time { return now }))
		claims := jwt.MapClaims{}
		_, err := p.ParseWithClaims(token, claims, func(t *jwt.Token) (interface{}, error) {
			kid, _ := t.Header["kid"].(string)
			if kid == "" {
				return nil, errors.New("jwt_missing_kid")
			}
			if m == specMutPrevAlwaysOK {
				specAllKeysMu.Lock()
				defer specAllKeysMu.Unlock()
				if pub, ok := specAllKeys[kid]; ok {
					return pub, nil
				}
				return nil, errors.New("jwt_unknown_kid")
			}
			if trust.Current != nil && kid == specRefKid(trust.Current) {
				return trust.Current, nil
			}
			if trust.Previous != nil && kid == specRefKid(trust.Previous) {
				return trust.Previous, nil
			}
			return nil, errors.New("jwt_unknown_kid")
		})
		if err != nil {
			return true, err
		}
		if claims["exp"] == nil {
			return true, errors.New("exp_required")
		}
		if s, _ := claims["jti"].(string); s == "" {
			return true, errors.New("jti_required")
		}
		if s, _ := claims["sub"].(string); s == "" {
			return true, errors.New("sub_required")
		}
		if m != specMutAudIgnored {
			if claims["aud"] == nil {
				return true, errors.New("jwt_missing_aud")
			}
			aud, err := claims.GetAudience()
			if err != nil || len(aud) != 1 || aud[0] != want.LocalID {
				return true, errors.New("jwt_wrong_aud")
			}
		}
		if m != specMutIssIgnored {
			if iss, _ := claims["iss"].(string); iss == "" || iss != want.RootID {
				return true, errors.New("jwt_wrong_issuer")
			}
		}
		if role, _ := claims["role"].(string); role != want.Role {
			return true, fmt.Errorf("role_refused: %q", role)
		}
		if jti, _ := claims["jti"].(string); trust.Blacklisted != nil && trust.Blacklisted(jti) {
			return true, errors.New("revoked")
		}
		return false, nil
	}

	impl.SignToken = func(priv ed25519.PrivateKey, iss, sub, aud, role string, ttl time.Duration) (string, string, error) {
		jti := fmt.Sprintf("jti-%d", time.Now().UnixNano())
		now := time.Now()
		tok := jwt.NewWithClaims(jwt.SigningMethodEdDSA, jwt.MapClaims{
			"iss": iss, "sub": sub, "aud": aud, "role": role, "jti": jti,
			"iat": now.Unix(), "exp": now.Add(ttl).Unix(),
		})
		tok.Header["kid"] = specRefKid(priv.Public().(ed25519.PublicKey))
		s, err := tok.SignedString(priv)
		return s, jti, err
	}

	impl.SignRevocations = func(priv ed25519.PrivateKey, seq uint64, e []specRevEntry) ([]byte, error) {
		return json.Marshal(specRevMsg{Seq: seq, Entries: e, Sig: ed25519.Sign(priv, specRevPayload(seq, e))})
	}
	impl.VerifyRevocations = func(trust specLinkTrust, msg []byte) (uint64, []specRevEntry, error) {
		var r specRevMsg
		if err := json.Unmarshal(msg, &r); err != nil {
			return 0, nil, err
		}
		if trust.Current == nil || !ed25519.Verify(trust.Current, specRevPayload(r.Seq, r.Entries), r.Sig) {
			return 0, nil, errors.New("bad_signature")
		}
		if m != specMutSeqIgnored && r.Seq <= trust.LastSeq {
			return 0, nil, errors.New("stale_seq")
		}
		return r.Seq, r.Entries, nil
	}

	impl.SignLinkKeys = func(oldPriv ed25519.PrivateKey, newCur, prev ed25519.PublicKey, seq uint64) ([]byte, error) {
		return json.Marshal(specKeysMsg{CurrentPub: newCur, PreviousPub: prev, Seq: seq, Sig: ed25519.Sign(oldPriv, specKeysPayload(newCur, prev, seq))})
	}
	impl.ApplyLinkKeys = func(trust specLinkTrust, msg []byte) (specLinkTrust, error) {
		var k specKeysMsg
		if err := json.Unmarshal(msg, &k); err != nil {
			return trust, err
		}
		if trust.Current == nil || !ed25519.PublicKey(k.PreviousPub).Equal(trust.Current) ||
			!ed25519.Verify(trust.Current, specKeysPayload(k.CurrentPub, k.PreviousPub, k.Seq), k.Sig) {
			return trust, errors.New("chain_broken")
		}
		if m != specMutSeqIgnored && k.Seq <= trust.LastSeq {
			return trust, errors.New("stale_seq")
		}
		out := trust
		out.Previous, out.Current, out.LastSeq = trust.Current, ed25519.PublicKey(k.CurrentPub), k.Seq
		return out, nil
	}
	return impl
}

// ── forging helpers (independent of the signer under test) ───────────────────

type specKey struct {
	pub  ed25519.PublicKey
	priv ed25519.PrivateKey
}

func specNewKey(t *testing.T) specKey {
	t.Helper()
	pub, priv, err := ed25519.GenerateKey(rand.Reader)
	if err != nil {
		t.Fatal(err)
	}
	specAllKeysMu.Lock()
	specAllKeys[specRefKid(pub)] = pub
	specAllKeysMu.Unlock()
	return specKey{pub, priv}
}

var (
	specRSAOnce sync.Once
	specRSAKey  *rsa.PrivateKey
)

func specRSA(t *testing.T) *rsa.PrivateKey {
	specRSAOnce.Do(func() {
		k, err := rsa.GenerateKey(rand.Reader, 2048)
		if err != nil {
			t.Fatal(err)
		}
		specRSAKey = k
	})
	return specRSAKey
}

// specBaseClaims is a valid link token for the child→parent direction (role relay-child, sub X, aud P).
func specBaseClaims(jti string) jwt.MapClaims {
	now := time.Now()
	return jwt.MapClaims{
		"iss": specRootID, "sub": specChildID, "aud": specParentID, "role": specRoleChild,
		"jti": jti, "iat": now.Unix(), "exp": now.Add(time.Hour).Unix(),
	}
}

func specForge(t *testing.T, method jwt.SigningMethod, key any, kid any, c jwt.MapClaims) string {
	t.Helper()
	tok := jwt.NewWithClaims(method, c)
	if kid != nil {
		tok.Header["kid"] = kid
	}
	s, err := tok.SignedString(key)
	if err != nil {
		t.Fatalf("forge: %v", err)
	}
	return s
}

// ── conformance cases ────────────────────────────────────────────────────────

// specCase returns "" when the verifier behaves as specified, otherwise why not.
type specCase struct {
	Name string
	Run  func(t *testing.T, impl *specLinkImpl) string
}

type specVerdict struct {
	trust specLinkTrust
	tok   string
	want  specLinkWant
}

func (v specVerdict) ask(impl *specLinkImpl) (permanent bool, err error) {
	return impl.VerifyToken(v.trust, v.tok, v.want, time.Now())
}

func specAccept(impl *specLinkImpl, v specVerdict) string {
	if _, err := v.ask(impl); err != nil {
		return "must be accepted, refused: " + err.Error()
	}
	return ""
}

// specRefuseWithCode is specRefuse plus the stable refusal code (checked when the impl exposes Code).
func specRefuseWithCode(impl *specLinkImpl, v specVerdict, code string) string {
	_, err := v.ask(impl)
	if err == nil {
		return "must be refused, accepted"
	}
	if impl.Code != nil {
		if got := impl.Code(err); got != code {
			return fmt.Sprintf("refusal code %q, want %q (%v)", got, code, err)
		}
	}
	return ""
}

func specRefuse(impl *specLinkImpl, v specVerdict) string {
	if _, err := v.ask(impl); err == nil {
		return "must be refused, accepted"
	}
	return ""
}

func specRefusePermanent(impl *specLinkImpl, v specVerdict) string {
	permanent, err := v.ask(impl)
	if err == nil {
		return "must be refused, accepted"
	}
	if !permanent {
		return "the refusal must be permanent (the child must not retry): " + err.Error()
	}
	return ""
}

var childWant = specLinkWant{LocalID: specParentID, RootID: specRootID, Role: specRoleChild}

// specLinkCases is the whole table. Names are stable: the mutants are expected to fail them by name.
func specLinkCases() []specCase {
	return []specCase{
		// ── accepted ──
		{"accept_child_token", func(t *testing.T, impl *specLinkImpl) string {
			k := specNewKey(t)
			tok := specForge(t, jwt.SigningMethodEdDSA, k.priv, impl.KidOf(k.pub), specBaseClaims("j1"))
			return specAccept(impl, specVerdict{specLinkTrust{Current: k.pub}, tok, childWant})
		}},
		{"accept_parent_token_push_direction", func(t *testing.T, impl *specLinkImpl) string {
			k := specNewKey(t)
			c := specBaseClaims("j2")
			c["sub"], c["aud"], c["role"] = specParentID, specChildID, specRoleParent
			tok := specForge(t, jwt.SigningMethodEdDSA, k.priv, impl.KidOf(k.pub), c)
			return specAccept(impl, specVerdict{specLinkTrust{Current: k.pub}, tok, specLinkWant{LocalID: specChildID, RootID: specRootID, Role: specRoleParent}})
		}},
		{"accept_previous_key_during_double_acceptation", func(t *testing.T, impl *specLinkImpl) string {
			old, cur := specNewKey(t), specNewKey(t)
			tok := specForge(t, jwt.SigningMethodEdDSA, old.priv, impl.KidOf(old.pub), specBaseClaims("j3"))
			return specAccept(impl, specVerdict{specLinkTrust{Current: cur.pub, Previous: old.pub}, tok, childWant})
		}},
		// ── test 1: signature ──
		{"refuse_token_signed_by_another_ed25519_key", func(t *testing.T, impl *specLinkImpl) string {
			root, evil := specNewKey(t), specNewKey(t)
			// the attacker claims the root's kid but signs with its own key
			tok := specForge(t, jwt.SigningMethodEdDSA, evil.priv, impl.KidOf(root.pub), specBaseClaims("j4"))
			return specRefuse(impl, specVerdict{specLinkTrust{Current: root.pub}, tok, childWant})
		}},
		// ── test 2: algorithm confusion ──
		{"refuse_hs256_with_root_public_key_as_hmac_secret_raw", func(t *testing.T, impl *specLinkImpl) string {
			root := specNewKey(t)
			tok := specForge(t, jwt.SigningMethodHS256, []byte(root.pub), impl.KidOf(root.pub), specBaseClaims("j5"))
			return specRefuse(impl, specVerdict{specLinkTrust{Current: root.pub}, tok, childWant})
		}},
		{"refuse_hs256_with_root_public_key_as_hmac_secret_der", func(t *testing.T, impl *specLinkImpl) string {
			root := specNewKey(t)
			der, err := x509.MarshalPKIXPublicKey(root.pub)
			if err != nil {
				t.Fatal(err)
			}
			tok := specForge(t, jwt.SigningMethodHS256, der, impl.KidOf(root.pub), specBaseClaims("j6"))
			return specRefuse(impl, specVerdict{specLinkTrust{Current: root.pub}, tok, childWant})
		}},
		{"refuse_alg_none", func(t *testing.T, impl *specLinkImpl) string {
			root := specNewKey(t)
			tok := specForge(t, jwt.SigningMethodNone, jwt.UnsafeAllowNoneSignatureType, impl.KidOf(root.pub), specBaseClaims("j7"))
			return specRefuse(impl, specVerdict{specLinkTrust{Current: root.pub}, tok, childWant})
		}},
		{"refuse_rs256", func(t *testing.T, impl *specLinkImpl) string {
			root := specNewKey(t)
			tok := specForge(t, jwt.SigningMethodRS256, specRSA(t), impl.KidOf(root.pub), specBaseClaims("j8"))
			return specRefuse(impl, specVerdict{specLinkTrust{Current: root.pub}, tok, childWant})
		}},
		{"refuse_es256", func(t *testing.T, impl *specLinkImpl) string {
			root := specNewKey(t)
			ec, err := ecdsa.GenerateKey(elliptic.P256(), rand.Reader)
			if err != nil {
				t.Fatal(err)
			}
			tok := specForge(t, jwt.SigningMethodES256, ec, impl.KidOf(root.pub), specBaseClaims("j9"))
			return specRefuse(impl, specVerdict{specLinkTrust{Current: root.pub}, tok, childWant})
		}},
		{"refuse_unknown_kid", func(t *testing.T, impl *specLinkImpl) string {
			root := specNewKey(t)
			tok := specForge(t, jwt.SigningMethodEdDSA, root.priv, "no-such-kid", specBaseClaims("j10"))
			return specRefuseWithCode(impl, specVerdict{specLinkTrust{Current: root.pub}, tok, childWant}, "jwt_unknown_kid")
		}},
		{"refuse_absent_kid", func(t *testing.T, impl *specLinkImpl) string {
			root := specNewKey(t)
			tok := specForge(t, jwt.SigningMethodEdDSA, root.priv, nil, specBaseClaims("j11"))
			return specRefuseWithCode(impl, specVerdict{specLinkTrust{Current: root.pub}, tok, childWant}, "jwt_missing_kid")
		}},
		{"refuse_non_string_kid", func(t *testing.T, impl *specLinkImpl) string {
			root := specNewKey(t)
			tok := specForge(t, jwt.SigningMethodEdDSA, root.priv, 42, specBaseClaims("j11b"))
			return specRefuse(impl, specVerdict{specLinkTrust{Current: root.pub}, tok, childWant})
		}},
		{"refuse_empty_and_malformed_tokens", func(t *testing.T, impl *specLinkImpl) string {
			root := specNewKey(t)
			for _, tok := range []string{"", "a.b", "a.b.c", "....", "not a jwt"} {
				if s := specRefuse(impl, specVerdict{specLinkTrust{Current: root.pub}, tok, childWant}); s != "" {
					return fmt.Sprintf("%q: %s", tok, s)
				}
			}
			return ""
		}},
		// ── test 3: audience ──
		{"refuse_token_presented_to_another_relay_aud_mismatch", func(t *testing.T, impl *specLinkImpl) string {
			root := specNewKey(t)
			tok := specForge(t, jwt.SigningMethodEdDSA, root.priv, impl.KidOf(root.pub), specBaseClaims("j12")) // aud = relay-p
			return specRefusePermanent(impl, specVerdict{specLinkTrust{Current: root.pub}, tok, specLinkWant{LocalID: "relay-q", RootID: specRootID, Role: specRoleChild}})
		}},
		{"refuse_absent_aud", func(t *testing.T, impl *specLinkImpl) string {
			root := specNewKey(t)
			c := specBaseClaims("j13")
			delete(c, "aud")
			tok := specForge(t, jwt.SigningMethodEdDSA, root.priv, impl.KidOf(root.pub), c)
			return specRefuseWithCode(impl, specVerdict{specLinkTrust{Current: root.pub}, tok, childWant}, "jwt_missing_aud")
		}},
		{"refuse_audience_list_naming_several_verifiers", func(t *testing.T, impl *specLinkImpl) string {
			root := specNewKey(t)
			c := specBaseClaims("j13b")
			c["aud"] = []string{specParentID, "relay-q"} // a token valid for ONE verifier only
			tok := specForge(t, jwt.SigningMethodEdDSA, root.priv, impl.KidOf(root.pub), c)
			return specRefuse(impl, specVerdict{specLinkTrust{Current: root.pub}, tok, childWant})
		}},
		// ── issuer (R1): the token must come from THE root this relay trusts ──
		{"refuse_issuer_other_than_the_configured_root", func(t *testing.T, impl *specLinkImpl) string {
			root := specNewKey(t)
			c := specBaseClaims("j13c")
			c["iss"] = "some-other-relay" // signed by the right key, claiming another origin
			tok := specForge(t, jwt.SigningMethodEdDSA, root.priv, impl.KidOf(root.pub), c)
			return specRefuseWithCode(impl, specVerdict{specLinkTrust{Current: root.pub}, tok, childWant}, "jwt_wrong_issuer")
		}},
		{"refuse_absent_issuer", func(t *testing.T, impl *specLinkImpl) string {
			root := specNewKey(t)
			c := specBaseClaims("j13d")
			delete(c, "iss")
			tok := specForge(t, jwt.SigningMethodEdDSA, root.priv, impl.KidOf(root.pub), c)
			return specRefuseWithCode(impl, specVerdict{specLinkTrust{Current: root.pub}, tok, childWant}, "jwt_wrong_issuer")
		}},
		// ── test 4: role ──
		{"refuse_relay_child_presented_as_parent", func(t *testing.T, impl *specLinkImpl) string {
			root := specNewKey(t)
			// we are the child X (push direction): we only accept a relay-parent token whose aud is us
			c2 := specBaseClaims("j14b")
			c2["aud"] = specChildID
			tok2 := specForge(t, jwt.SigningMethodEdDSA, root.priv, impl.KidOf(root.pub), c2) // still role relay-child
			return specRefusePermanent(impl, specVerdict{specLinkTrust{Current: root.pub}, tok2, specLinkWant{LocalID: specChildID, RootID: specRootID, Role: specRoleParent}})
		}},
		{"refuse_relay_parent_presented_as_child", func(t *testing.T, impl *specLinkImpl) string {
			root := specNewKey(t)
			c := specBaseClaims("j15")
			c["role"] = specRoleParent
			tok := specForge(t, jwt.SigningMethodEdDSA, root.priv, impl.KidOf(root.pub), c)
			return specRefusePermanent(impl, specVerdict{specLinkTrust{Current: root.pub}, tok, childWant})
		}},
		{"refuse_unknown_and_absent_role", func(t *testing.T, impl *specLinkImpl) string {
			root := specNewKey(t)
			for _, role := range []any{"agent", "admin", "plugin", "RELAY-CHILD", "", nil} {
				c := specBaseClaims("j16")
				if role == nil {
					delete(c, "role")
				} else {
					c["role"] = role
				}
				tok := specForge(t, jwt.SigningMethodEdDSA, root.priv, impl.KidOf(root.pub), c)
				if s := specRefuse(impl, specVerdict{specLinkTrust{Current: root.pub}, tok, childWant}); s != "" {
					return fmt.Sprintf("role %v: %s", role, s)
				}
			}
			return ""
		}},
		{"refuse_legacy_role_relay_hs256_permanently", func(t *testing.T, impl *specLinkImpl) string {
			root := specNewKey(t)
			c := specBaseClaims("j17")
			c["role"] = specLegacyRoleRelay
			delete(c, "aud") // a v3.0.3 token has no aud
			tok := specForge(t, jwt.SigningMethodHS256, []byte("a-v3.0.3-JWT_SECRET_KEY"), nil, c)
			return specRefusePermanent(impl, specVerdict{specLinkTrust{Current: root.pub}, tok, childWant})
		}},
		// ── claims hygiene ──
		{"refuse_expired_token", func(t *testing.T, impl *specLinkImpl) string {
			root := specNewKey(t)
			c := specBaseClaims("j18")
			c["exp"] = time.Now().Add(-time.Minute).Unix()
			tok := specForge(t, jwt.SigningMethodEdDSA, root.priv, impl.KidOf(root.pub), c)
			return specRefuse(impl, specVerdict{specLinkTrust{Current: root.pub}, tok, childWant})
		}},
		{"refuse_token_without_exp", func(t *testing.T, impl *specLinkImpl) string {
			root := specNewKey(t)
			c := specBaseClaims("j19")
			delete(c, "exp")
			tok := specForge(t, jwt.SigningMethodEdDSA, root.priv, impl.KidOf(root.pub), c)
			return specRefuse(impl, specVerdict{specLinkTrust{Current: root.pub}, tok, childWant})
		}},
		{"refuse_token_without_jti", func(t *testing.T, impl *specLinkImpl) string {
			root := specNewKey(t)
			c := specBaseClaims("")
			delete(c, "jti")
			tok := specForge(t, jwt.SigningMethodEdDSA, root.priv, impl.KidOf(root.pub), c)
			return specRefuse(impl, specVerdict{specLinkTrust{Current: root.pub}, tok, childWant})
		}},
		{"refuse_token_without_sub", func(t *testing.T, impl *specLinkImpl) string {
			root := specNewKey(t)
			c := specBaseClaims("j20")
			delete(c, "sub")
			tok := specForge(t, jwt.SigningMethodEdDSA, root.priv, impl.KidOf(root.pub), c)
			return specRefuse(impl, specVerdict{specLinkTrust{Current: root.pub}, tok, childWant})
		}},
		{"refuse_blacklisted_jti", func(t *testing.T, impl *specLinkImpl) string {
			root := specNewKey(t)
			tok := specForge(t, jwt.SigningMethodEdDSA, root.priv, impl.KidOf(root.pub), specBaseClaims("revoked-jti"))
			trust := specLinkTrust{Current: root.pub, Blacklisted: func(j string) bool { return j == "revoked-jti" }}
			return specRefuse(impl, specVerdict{trust, tok, childWant})
		}},
		// ── test 5: rotation ──
		{"refuse_previous_key_after_retire_link_previous", func(t *testing.T, impl *specLinkImpl) string {
			old, cur := specNewKey(t), specNewKey(t)
			tok := specForge(t, jwt.SigningMethodEdDSA, old.priv, impl.KidOf(old.pub), specBaseClaims("j21"))
			// Previous = nil: the window is closed. The token was fine a moment ago…
			if s := specAccept(impl, specVerdict{specLinkTrust{Current: cur.pub, Previous: old.pub}, tok, childWant}); s != "" {
				return "during the window: " + s
			}
			// …and is a replay now.
			return specRefuse(impl, specVerdict{specLinkTrust{Current: cur.pub}, tok, childWant})
		}},
		{"link_keys_valid_chain_rotates_the_trust", func(t *testing.T, impl *specLinkImpl) string {
			old, next := specNewKey(t), specNewKey(t)
			msg, err := impl.SignLinkKeys(old.priv, next.pub, old.pub, 7)
			if err != nil {
				return "sign: " + err.Error()
			}
			got, err := impl.ApplyLinkKeys(specLinkTrust{Current: old.pub, LastSeq: 6}, msg)
			if err != nil {
				return "must be accepted: " + err.Error()
			}
			if !got.Current.Equal(next.pub) || !got.Previous.Equal(old.pub) {
				return "after the rotation current must be the new key and previous the old one"
			}
			// the token of the new key is now accepted, the one of the old key too (window)
			tok := specForge(t, jwt.SigningMethodEdDSA, next.priv, impl.KidOf(next.pub), specBaseClaims("j22"))
			return specAccept(impl, specVerdict{got, tok, childWant})
		}},
		{"link_keys_not_chained_to_the_anchor_is_refused_and_trust_unchanged", func(t *testing.T, impl *specLinkImpl) string {
			anchor, evil, forged := specNewKey(t), specNewKey(t), specNewKey(t)
			// a compromised intermediate parent signs a rotation with ITS key, claiming the anchor as previous
			msg, err := impl.SignLinkKeys(evil.priv, forged.pub, anchor.pub, 9)
			if err != nil {
				return "sign: " + err.Error()
			}
			trust := specLinkTrust{Current: anchor.pub, LastSeq: 8}
			got, err := impl.ApplyLinkKeys(trust, msg)
			if err == nil {
				return "a rotation that does not chain back to the anchor must be refused"
			}
			if !got.Current.Equal(anchor.pub) || got.Previous != nil || got.LastSeq != 8 {
				return "the trust must be left unchanged after a refused link_keys"
			}
			return ""
		}},
		{"link_keys_self_signed_by_the_new_key_is_refused", func(t *testing.T, impl *specLinkImpl) string {
			anchor, next := specNewKey(t), specNewKey(t)
			msg, err := impl.SignLinkKeys(next.priv, next.pub, anchor.pub, 3)
			if err != nil {
				return "sign: " + err.Error()
			}
			if _, err := impl.ApplyLinkKeys(specLinkTrust{Current: anchor.pub}, msg); err == nil {
				return "a key cannot vouch for itself"
			}
			return ""
		}},
		{"link_keys_replayed_seq_is_refused", func(t *testing.T, impl *specLinkImpl) string {
			old, next := specNewKey(t), specNewKey(t)
			msg, err := impl.SignLinkKeys(old.priv, next.pub, old.pub, 4)
			if err != nil {
				return "sign: " + err.Error()
			}
			if _, err := impl.ApplyLinkKeys(specLinkTrust{Current: old.pub, LastSeq: 4}, msg); err == nil {
				return "seq equal to the last accepted one must be refused"
			}
			if _, err := impl.ApplyLinkKeys(specLinkTrust{Current: old.pub, LastSeq: 5}, msg); err == nil {
				return "seq lower than the last accepted one must be refused"
			}
			return ""
		}},
		// ── test 6: revocation messages ──
		{"link_revocations_valid_is_accepted", func(t *testing.T, impl *specLinkImpl) string {
			root := specNewKey(t)
			entries := []specRevEntry{{"jti-a", time.Now().Add(time.Hour).Unix()}, {"jti-b", time.Now().Add(2 * time.Hour).Unix()}}
			msg, err := impl.SignRevocations(root.priv, 5, entries)
			if err != nil {
				return "sign: " + err.Error()
			}
			seq, got, err := impl.VerifyRevocations(specLinkTrust{Current: root.pub, LastSeq: 4}, msg)
			if err != nil {
				return "must be accepted: " + err.Error()
			}
			if seq != 5 || len(got) != 2 || got[0].JTI != "jti-a" || got[1].JTI != "jti-b" {
				return fmt.Sprintf("seq/entries not returned faithfully: %d %v", seq, got)
			}
			return ""
		}},
		{"link_revocations_seq_equal_or_lower_is_refused", func(t *testing.T, impl *specLinkImpl) string {
			root := specNewKey(t)
			msg, err := impl.SignRevocations(root.priv, 5, []specRevEntry{{"jti-a", time.Now().Add(time.Hour).Unix()}})
			if err != nil {
				return "sign: " + err.Error()
			}
			if _, _, err := impl.VerifyRevocations(specLinkTrust{Current: root.pub, LastSeq: 5}, msg); err == nil {
				return "seq == last accepted must be refused"
			}
			if _, _, err := impl.VerifyRevocations(specLinkTrust{Current: root.pub, LastSeq: 9}, msg); err == nil {
				return "seq < last accepted (replay of an older list) must be refused"
			}
			return ""
		}},
		{"link_revocations_signed_by_a_foreign_key_is_refused", func(t *testing.T, impl *specLinkImpl) string {
			root, evil := specNewKey(t), specNewKey(t)
			msg, err := impl.SignRevocations(evil.priv, 6, nil)
			if err != nil {
				return "sign: " + err.Error()
			}
			if _, _, err := impl.VerifyRevocations(specLinkTrust{Current: root.pub, LastSeq: 5}, msg); err == nil {
				return "a revocation list signed by another key must be refused"
			}
			return ""
		}},
		{"link_revocations_signed_by_the_previous_key_is_refused", func(t *testing.T, impl *specLinkImpl) string {
			old, cur := specNewKey(t), specNewKey(t)
			msg, err := impl.SignRevocations(old.priv, 6, nil)
			if err != nil {
				return "sign: " + err.Error()
			}
			// spec: signed by the root `current` key
			if _, _, err := impl.VerifyRevocations(specLinkTrust{Current: cur.pub, Previous: old.pub, LastSeq: 5}, msg); err == nil {
				return "only the current key signs link_revocations"
			}
			return ""
		}},
		{"link_revocations_tampered_message_is_refused", func(t *testing.T, impl *specLinkImpl) string {
			root := specNewKey(t)
			msg, err := impl.SignRevocations(root.priv, 6, []specRevEntry{{"jti-a", time.Now().Add(time.Hour).Unix()}})
			if err != nil {
				return "sign: " + err.Error()
			}
			bad := append([]byte(nil), msg...)
			bad[len(bad)/2] ^= 0x01
			if _, _, err := impl.VerifyRevocations(specLinkTrust{Current: root.pub, LastSeq: 5}, bad); err == nil {
				return "a message altered in transit must be refused"
			}
			return ""
		}},
		{"link_revocations_full_list_after_a_cut_is_accepted", func(t *testing.T, impl *specLinkImpl) string {
			root := specNewKey(t)
			exp := time.Now().Add(time.Hour).Unix()
			// the child saw seq 3, missed 4 and 5; on reconnection it gets the FULL list at seq 5
			full := []specRevEntry{{"old-1", exp}, {"old-2", exp}, {"new-4", exp}, {"new-5", exp}}
			msg, err := impl.SignRevocations(root.priv, 5, full)
			if err != nil {
				return "sign: " + err.Error()
			}
			seq, got, err := impl.VerifyRevocations(specLinkTrust{Current: root.pub, LastSeq: 3}, msg)
			if err != nil || seq != 5 || len(got) != 4 {
				return fmt.Sprintf("the full list after a cut must be accepted: seq=%d n=%d err=%v", seq, len(got), err)
			}
			return ""
		}},
		// ── round trip with the real signer (format cross-check) ──
		{"signer_output_is_accepted_by_the_verifier_and_has_the_specified_shape", func(t *testing.T, impl *specLinkImpl) string {
			root := specNewKey(t)
			tok, jti, err := impl.SignToken(root.priv, specRootID, specChildID, specParentID, specRoleChild, time.Hour)
			if err != nil || jti == "" {
				return fmt.Sprintf("sign: jti=%q err=%v", jti, err)
			}
			parsed, _, err := jwt.NewParser().ParseUnverified(tok, jwt.MapClaims{})
			if err != nil {
				return "unparseable token: " + err.Error()
			}
			c := parsed.Claims.(jwt.MapClaims)
			if parsed.Header["alg"] != "EdDSA" || parsed.Header["kid"] != impl.KidOf(root.pub) {
				return fmt.Sprintf("header must be alg=EdDSA + kid of the root key, got %v", parsed.Header)
			}
			for _, k := range []string{"iss", "sub", "aud", "role", "jti", "iat", "exp"} {
				if c[k] == nil {
					return "claim " + k + " is mandatory"
				}
			}
			if c["jti"] != jti || c["role"] != specRoleChild || c["sub"] != specChildID {
				return "claims do not carry what was asked"
			}
			return specAccept(impl, specVerdict{specLinkTrust{Current: root.pub}, tok, childWant})
		}},
	}
}

// ── oracle tests (run today) ─────────────────────────────────────────────────

func specFailures(t *testing.T, impl *specLinkImpl) map[string]string {
	t.Helper()
	out := map[string]string{}
	for _, c := range specLinkCases() {
		if why := c.Run(t, impl); why != "" {
			out[c.Name] = why
		}
	}
	return out
}

// The cases are right: a correct verifier passes every one of them.
func TestSpecLink_OraclePassesEveryCase(t *testing.T) {
	if f := specFailures(t, specOracle(specNoMutant)); len(f) != 0 {
		t.Fatalf("the reference verifier fails cases (the cases are wrong): %v", f)
	}
}

// The cases bite: each mutant is caught by the cases built for it (mutation tests of the L1 plan, §3-12).
func TestSpecLink_MutantsAreKilled(t *testing.T) {
	for _, tc := range []struct {
		mutant specMutant
		killBy []string
	}{
		{specMutAudIgnored, []string{"refuse_token_presented_to_another_relay_aud_mismatch", "refuse_absent_aud"}},
		{specMutPrevAlwaysOK, []string{"refuse_previous_key_after_retire_link_previous"}},
		{specMutIssIgnored, []string{"refuse_issuer_other_than_the_configured_root", "refuse_absent_issuer"}},
		{specMutSeqIgnored, []string{"link_revocations_seq_equal_or_lower_is_refused", "link_keys_replayed_seq_is_refused"}},
	} {
		t.Run(string(tc.mutant), func(t *testing.T) {
			f := specFailures(t, specOracle(tc.mutant))
			if len(f) == 0 {
				t.Fatalf("mutant %q survives: no case detects it", tc.mutant)
			}
			for _, name := range tc.killBy {
				if _, ok := f[name]; !ok {
					t.Errorf("mutant %q must be killed by %q, only %v fail", tc.mutant, name, f)
				}
			}
		})
	}
}
